### ISSUE TITLE
Menu Issue?

### ISSUE THREAD

**Issue by ghost** [mrkev/Iroh#5]
As noted by Trevor, it seems the API is returning dining-hall-menus
for cafes?
https://github.com/genkimarshall/bigredapp-android/issues/38

**Comment by mrkev** [comment]
Hmmm, will look into it

**Comment by genkimarshall** [comment]
No rush no rush :+1:

**Comment by mrkev** [comment]
I should really big red hack this lol

**Comment by genkimarshall** [comment]
Haha :P

**Comment by genkimarshall** [comment]
Cleaning up my opened issues I don't think this is an issue anymore, ha
